### ISSUE TITLE
Windows specific: <cr> after command not executed in ipyhton 

### ISSUE THREAD

**Issue by gilbh** [milanglacier/yarepl.nvim#12]
Great plugin!

Sending line via `:REPLSendLine` on Windows/ipython REPL does not send the newline and line is not executed:
![image](https://github.com/milanglacier/yarepl.nvim/assets/39532610/c13d8cef-034d-438f-88ec-70f89685e887)

This issue seems to be similar to this:
https://github.com/kassio/neoterm/issues/171

**Comment by milanglacier** [comment]
This is weird.

I already appended `\r` as the end code for `ipython`.

I don’t use neovim on windows, maybe I can suggest you some patches later. But you may have to test them to see if it works.

**Comment by gilbh** [comment]
Thanks. Let me know and I will test and get back with results.

**Comment by milanglacier** [comment]
After reading some issues, I think this is not a problem of `yarepl`, it should be a problem of `chansend` (the neovim builtin function).

I a really hackish way to make it work: you need to append an additional `\r` to the text, but you cannot append `\r` at the same string of the text you send to the REPl. Instead you need to wait for some times to send another `\r` after sending the text. Is it possible that if the text stream flushes too quickly, then the `\r` will be swallowed?

The reference is here: https://github.com/urbainvaes/vim-ripple/issues/12

Please try the branch `hack/windows-ipython` and to see if this works for you.


Off topic: This issue just deepens my understanding about that how **terminal-friendly** windows is, once again. Too many quirks, too many hacks,

**Comment by gilbh** [comment]
> After reading some issues, I think this is not a problem of `yarepl`, it should be a problem of `chansend` (the neovim builtin function).
> 
> I a really hackish way to make it work: you need to append an additional `\r` to the text, but you cannot append `\r` at the same string of the text you send to the REPl. Instead you need to wait for some times to send another `\r` after sending the text. Is it possible that if the text stream flushes too quickly, then the `\r` will be swallowed?
> 
> The reference is here: [urbainvaes/vim-ripple#12](https://github.com/urbainvaes/vim-ripple/issues/12)
> 
> Please try the branch `hack/windows-ipython` and to see if this works for you.
> 
> Off topic: This issue just deepens my understanding about that how **terminal-friendly** windows is, once again. Too many quirks, too many hacks,

Happy to! How do I test branch `hack/windows-ipython`? Do I change something in the Lazy setup command of `'milanglacier/yarepl.nvim'` or do a curl/git close? Sorry for lame question, I am not experiences with github...
```
```

**Comment by milanglacier** [comment]
suppose previously your lazy spec is:

```
{'milanglacier/yarepl.nvim'}
```

now change it to

```
{'milanglacier/yarepl.nvim', branch = 'hack/windows-ipython'}
```

and call `Lazy update yarepl.nvim` to update the plugin spec.

**Comment by gilbh** [comment]
Wow, it seems that newline issue has been completely resolved. It's now working as it should!

Plus the `REPLExec` is fantastic (without quotes but working great).

I now can start converting my mappings and functions to use YAREPL. If I come into any issues, I'll let you know.

Thanks!!!

**Comment by milanglacier** [comment]
Great!

If it is possible, would you mind giving more test on the plain `python` REPL (not ipython), (and other REPLs like R, bash if possible)?

They uses different formatters and once they are all stable, I can merge it into the main branch.

**Comment by gilbh** [comment]
I tested vanilla python and it works great, so no issues there (at least from cursory testing). I can't say for the other REPLs as I don't work in these languages. I might have more on iptyhon after I migrate my .vimrc.
