### ISSUE TITLE
[FEATURE] Allow sending a range of lines

### ISSUE THREAD

**Issue by mhoirup** [milanglacier/yarepl.nvim#16]
vim-slime allows sending a range of lines to the selected window/repl. For example`:35,65SlimeSend` would send all lines starting from line 35 to 65. This is handy if you have blocks with indented blank lines in them for readability, e.g. function or class definitions, which wouldn't get picked up by the `:REPLSendMotion` command if using the paragraph text-object.

Can we get something similar in `yarepl`? I know there's `:REPLSendVisual`, but the constant visual selection would create an uncomfortable flickering.

**Comment by milanglacier** [comment]
This is not possible with yarepl's API design.

A vim command cannot accept a range and a count simultaneously. All yarepl's command relies on the count to identify the REPL's id.

If you wish to send a class/a function to REPL, I recommend you try `nvim-treesitter/text-objects`, which provides a lot of convenient text objects like an expression, a class, a function. Let's say you bind a class to `ac`, then you can just use `<LocalLeader>sac` to send a whole class to REPL.

Here's an workaround code that uses `vim.ui.input` to select the begin line and the end line and then send them to REPL.

```lua
local yarepl = require 'yarepl'

vim.api.nvim_create_user_command('REPLSendLines', function(opts)
    local id = opts.count
    local name = opts.args
    local current_buffer = vim.api.nvim_get_current_buf()

    vim.ui.input({ prompt = 'the begin line' }, function(bol)
        vim.ui.input({ prompt = 'the end line' }, function(eol)
            bol = tonumber(bol)
            eol = tonumber(eol)

            if bol and eol then
                local lines = vim.api.nvim_buf_get_lines(current_buffer, bol - 1, eol, false)
                yarepl._send_strings(id, name, current_buffer, lines)
            end
        end)
    end)
end, {
    count = true,
    nargs = '?',
    desc = [[
Send lines with specified line number to REPL `i` or the REPL that current buffer is attached to.
]],
})


```
