### ISSUE TITLE
quit R when running shiny app

### ISSUE THREAD

**Issue by Yousuf28** [milanglacier/yarepl.nvim#18]
When I run shiny app in RStudio, I can stop the R by hitting interrupt R button shown in below screenshot or I can hit ESC button to stop R. 
![Screenshot 2023-08-17 103142](https://github.com/milanglacier/yarepl.nvim/assets/31291716/f4587d94-254a-4462-99b6-14e9f3d8fbed)

How can I get similar behavior when I am using yarepl. How do I interrupt R?

![SharedScreenshot](https://github.com/milanglacier/yarepl.nvim/assets/31291716/361f2c87-9f21-4f38-8e9a-64fee028aae1)

**Comment by milanglacier** [comment]
send `Ctrl-C` to the terminal.

Two ways: `:REPLExec <Ctrl-v><Ctrl-c>` (`Ctrl-v` means send the next character literally)
or switch to the REPL buffer and press `Ctrl-C`
