### ISSUE TITLE
Expose more functions from `init.lua`

### ISSUE THREAD

**Issue by jack-dunham** [milanglacier/yarepl.nvim#20]
Hi there, 

Thanks for the great plugin.

I wish to write some of my own commands using your plugin, but this is very difficult to do as the API is very limited. Would you consider exposing functions such as `get_repl` and the like? Or is there a way to access these local functions using Lua?

Basically I was hoping to write command that would execute `REPLFocus` if a REPL exits, otherwise it execute `REPLStart`. I have a hacky way of doing this but it results in unnecessary notifications about REPLs (not)existing etc every time is execute the command.

Thanks!

**Comment by milanglacier** [comment]
there will be no way to access a private function outside its source.

I will expose more public APIs, thanks for your advice.

**Comment by milanglacier** [comment]
Besides, the reason I separate REPLFocus and REPLStart is the semantics would be ambiguous.

I mean, if you are using REPLFocus with a name and a ID, then it is hard to know whether the user actually wants to create a new REPL with the name or focus on the closest REPL to that ID with that name?

If you don’t care about the “find the closest REPL” stuffs, then the semantics would be clear, and in that case, exposing the APIs to achieve the functionality is reasonable to me.

**Comment by milanglacier** [comment]
You can now use `M._get_repl` to access this function.
