### ISSUE TITLE
[Feature request] Toggle command

### ISSUE THREAD

**Issue by ljnsn** [milanglacier/yarepl.nvim#6]
Could we get a `REPLToggle` command that combines hide and focus? Is there an easy way to find whether a repl is currently open so that I could add this myself in a mapping?

**Comment by milanglacier** [comment]
Yes, this is reasonable a feature request. I will add a new command `REPLHideOrFocus` which will has similar usage interface like `REPLFocus` and `REPLHide`.

**Comment by milanglacier** [comment]
The command `REPLHideOrFocus` has been added!
